import { NW_ENV } from 'bin/index.es';
import { BrowserWindow } from 'electron';
import { inject } from 'inversify';
import IApp from '../interface/app';
import CacheSystem from '../interface/cache';
import FileSystem from '../interface/file-system';
import IpcServer from '../interface/ipc-server';
import MainGlobal from '../interface/main-global';
import INextWriterMenu from '../interface/menu';
import SysInit from '../interface/sys-init';
import { TYPES } from '../types';

// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

// ============================================================
// This file is used to record the files managed by next-writer
// in the workstation.
// ============================================================
const WORKSTATION_JSON = '.nwriter.info.json';

const DEFAULT_WINDOW: BrowserWindowConstructorOptions = {
  height: 725,
  width: 1180,
  minWidth: 1000,
  minHeight: 400,
  frame: false,
  titleBarStyle: 'hidden',
  trafficLightPosition: { x: 28, y: 15 },
  vibrancy: 'under-window',
  visualEffectState: 'active',
  webPreferences: {
    preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
    nodeIntegration: true,
    contextIsolation: true
  }
};

/**
 * A factory class, which to create next-writer application and start server
 *
 * @author crazycodegame
 */
class NextWriter implements IApp {
  @inject(TYPES.SysInit) private _sysInit: SysInit;
  @inject(TYPES.CacheSystem) private cache: CacheSystem;
  @inject(TYPES.INextWriterMenu) private _menu: INextWriterMenu;
  @inject(TYPES.IpcServer) private _ipcServer: IpcServer;
  @inject(TYPES.MainGlobal) private _mainGlobal: MainGlobal;
  @inject(TYPES.FileSystem) private _fileSystem: FileSystem;

  // Because the `BrowserWindow` instance object is often used, an additional variable is defined here to reference the window object in then `mainGlobal` object
  // In fact, the `BrwoserWindow` instance is created in the `createWindow` method
  private _win: BrowserWindow;

  createWindow(): void {
    // If there already have a instance, close all listener of this instance
    if (this._win) {
      this._win.removeAllListeners();
    }
    this._win = new BrowserWindow(DEFAULT_WINDOW);

    // Open the DevTools in development environment
    if (NW_ENV === 'DEV') {
      this._win.webContents.openDevTools();
    }

    // Initial application system
    this._sysInit.init();

    // Create menu
    this.createWindow();

    // TODO: need to check cache system init
    // this.cache = new
  }
  createMenu(): void {
    // ..
  }
  destroy(): void {
    // ..
  }
}

export default NextWriter;
