import nodeFs from 'fs';
import nodePath from 'path';
import { BrowserWindow, BrowserWindowConstructorOptions, dialog } from 'electron';
import {
  CONFIG_DIR_NAME,
  CONFIG_JSON_NAME,
  IS_DEV,
  LOG_DIR_NAME,
  LOG_NAME,
  NW_CONFIG,
  ROOT_DIR_NAME
} from 'src/config/env';
import { inject, injectable } from 'inversify';
import INextApp from '../interface/next-app';
import INextCacheSystem from '../interface/next-cache-system';
import INextFileSystem from '../interface/next-file-system';
import INextIpcServer from '../interface/next-ipc-server';
import INextMenu from '../interface/next-menu';
import { TYPES } from '../types';
import INextStoreSystem from '../interface/next-store-system';
import { isEffectObject, isTrulyEmpty, removeEmpty } from 'src/tools/utils';
import ipcHanlders from '../ipc-handler';
import { APP_PROMOT } from 'src/tools/config';

// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

// ============================================================
// This file is used to record the files managed by next-writer
// in the workstation.
// ============================================================
const WORKSTATION_JSON = '.nwriter.info.json';

const DEFAULT_WINDOW: BrowserWindowConstructorOptions = {
  height: 725,
  width: 1180,
  minWidth: 1000,
  minHeight: 400,
  frame: false,
  titleBarStyle: 'hidden',
  trafficLightPosition: { x: 28, y: 15 },
  vibrancy: 'under-window',
  visualEffectState: 'active',
  webPreferences: {
    preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
    nodeIntegration: true,
    contextIsolation: true
  }
};

@injectable()
class NextApp implements INextApp {
  private _win: BrowserWindow;
  private _cache: INextCacheSystem;
  private _ipc: INextIpcServer;
  private _fileSystem: INextFileSystem;
  private _store: INextStoreSystem;
  private _menu: INextMenu;
  constructor(
    @inject(TYPES.INextCacheSystem) cache: INextCacheSystem,
    @inject(TYPES.INextIpcServer) ipc: INextIpcServer,
    @inject(TYPES.INextFileSystem) fileSystem: INextFileSystem,
    @inject(TYPES.INextStoreSystem) store: INextStoreSystem,
    @inject(TYPES.INextMenu) menu: INextMenu
  ) {
    this._cache = cache;
    this._ipc = ipc;
    this._fileSystem = fileSystem;
    this._store = store;
    this.createWindow = this.createWindow.bind(this);
    this._menu = menu;
  }
  async createWindow() {
    // Remove all listener if exist a application instance.
    if (this._win) {
      this._win.removeAllListeners();
    }

    this._win = new BrowserWindow(DEFAULT_WINDOW);

    // Store the current brwoserWindow
    this._store.setConfig('win', this._win);

    // Create a cache
    this._cache.init();

    // Read workstation record info: WORKSTATION_JSON
    await this.initFileSystem();

    // Mount ipc
    this._ipc.listen();
    // register ipc handler
    ipcHanlders.forEach(handler => this._ipc.registerHandler(handler));

    // Create menu
    this._menu.createMenu();

    if (IS_DEV) {
      this._win.webContents.openDevTools();
    }

    // Mount instance event
    this.mountInstanceEvent();

    // Mount global error handler
    this.mountGlobalErrorHandler();

    // ============================================================
    // Start load renderer process
    // ============================================================
    this._win.loadURL(MAIN_WINDOW_WEBPACK_ENTRY);
  }

  destroy(): void {
    this._ipc.destroy();
    this._cache.destroy();
    this._win = null;
  }

  /**
   * Read log, root, config path of current platform, and get workstation json content
   * set this all to store system
   * exmaple:
   * ------
   * root: ~/documents/nwriter/
   * config: ~/.config/nwriter/
   * log: ~/.local/state/nwriter/
   */
  private async initFileSystem() {
    // Get config, log, library path;
    const home = process.env.HOME || process.env.USERPROFILE;
    const macConfigDir = `${home}/.config/${CONFIG_DIR_NAME}`;
    const macLogDir = `${home}/.local/state/${LOG_DIR_NAME}`;
    const macLibraryDir = `${home}/documents/${ROOT_DIR_NAME}`;

    // For window platform
    const winConfigDir = `${home}\\${CONFIG_DIR_NAME}`;
    const winLogDir = `${home}\\${LOG_DIR_NAME}\\log`;
    const winLibraryDir = `${home}\\documents\\${ROOT_DIR_NAME}`;

    const configDir = process.platform === 'win32' ? winConfigDir : macConfigDir;
    const logDir = process.platform === 'win32' ? winLogDir : macLogDir;
    const rootDir = process.platform === 'win32' ? winLibraryDir : macLibraryDir;

    if (!(await this._fileSystem.isExist(configDir))) {
      await nodeFs.promises.mkdir(configDir, { recursive: true });
    }

    if (!(await this._fileSystem.isExist(logDir))) {
      await nodeFs.promises.mkdir(logDir, { recursive: true });
    }

    // if (!(await this._fileSystem.isExist(rootDir))) {
    //   await nodeFs.promises.mkdir(rootDir, { recursive: true });
    // }

    // Set config to store
    this._store.setConfigs({ logDir, rootDir, configDir });

    // Create log file if not exist
    if (!(await this._fileSystem.isExist(nodePath.join(logDir, LOG_NAME)))) {
      await nodeFs.promises.writeFile(nodePath.join(logDir, LOG_NAME), '', 'utf8');
    }

    // Read or create application config json file
    await this.initJsonConfig();

    // Read rootDir from store, since `initJsonConfig` function could change the value of rootDir
    const realRoot = this._store.getConfig('rootDir');

    if (isTrulyEmpty(realRoot)) {
      throw new Error('[nwriter] The workstation path is empty when initFileSystem');
    }

    if (!(await this._fileSystem.isExist(realRoot))) {
      await nodeFs.promises.mkdir(realRoot, { recursive: true });
    }

    const recordPath = nodePath.resolve(realRoot, WORKSTATION_JSON);

    let buffer = JSON.stringify({ children: [] });
    if (await this._fileSystem.isExist(recordPath)) {
      buffer = await nodeFs.promises.readFile(recordPath, { encoding: 'utf8' });
    }

    // Set library tree
    this._store.setConfig('libraryTree', JSON.parse(buffer));
  }

  /**
   * Process file: ~/.config/nwriter/nwriter.json
   */
  private async initJsonConfig(configFilePath?: string) {
    const defaultConfigDir = this._store.getConfig('configDir') ?? '';
    if (isTrulyEmpty(configFilePath) && isTrulyEmpty(defaultConfigDir)) {
      throw new Error(`[nwriter]Get empty path of config json file when invoke ${this.initJsonConfig.name}`);
    }
    const path = isTrulyEmpty(configFilePath) ? nodePath.join(defaultConfigDir, CONFIG_JSON_NAME) : configFilePath;

    if (!(await this._fileSystem.isExist(path))) {
      // Write default config to path
      this._fileSystem.writeFile(path, JSON.stringify(NW_CONFIG, null, 2));
      this._store.setConfig('renderConfig', NW_CONFIG);
      return;
    }

    // If exist a config file, like ~/.config/nwriter/nwriter.json
    // Read this file and update store.
    const buffer = await this._fileSystem.readFile(path);
    const jsonObj = removeEmpty(JSON.parse(buffer));
    const { root, ...restConfig } = jsonObj;
    // Reset root dir if have config item
    if (!isTrulyEmpty(root)) {
      this._store.setConfig('rootDir', root as string);
    }
    if (isEffectObject(restConfig)) {
      this._store.setConfig('renderConfig', restConfig);
    }
  }

  /**
   * Mount application event of an instance.
   */
  private mountInstanceEvent(): void {
    if (!this._win) {
      throw new Error('[nwriter] The application instance is empty.');
    }

    this._win.on('close', async e => {
      if (this._cache.hasModifed()) {
        const stopClose = await dialog.showMessageBox(this._win, {
          type: 'warning',
          buttons: ['取消', '确认'],
          defaultId: 1,
          message: '[next-writer] 有文件未保存，是否关闭应用？',
          title: '通知'
        });

        if (stopClose) {
          e.preventDefault();
          return;
        }
      }

      this._win.removeAllListeners();
      this.destroy();
    });
  }

  private mountGlobalErrorHandler(): void {
    process.on('uncaughtException', error => {
      dialog.showErrorBox('main process error', `${APP_PROMOT} ${error.message}`);
    });

    process.on('unhandledRejection', reject => {
      const msg =
        typeof reject === 'string' ? reject : reject instanceof Error ? reject.message : 'Unrecognized type of reject';
      dialog.showErrorBox('main process promise reject', `${APP_PROMOT} ${msg}`);
    });
  }
}

export default NextApp;
